---

- hosts: localhost
  gather_facts: yes

  tasks:
  - name: create new vpc
    ec2_vpc_net:
      state: present
      name: myvpc
      cidr_block: 172.16.0.0/24
      region: us-east-2


  - name: TO DISPLAY VPC_ID
    command: aws ec2 describe-vpcs --filter Name=tag:Name,Values=myvpc --query Vpcs[].VpcId --output text
    register: VPC_ID

    #      - debug: var=VPC_ID.stdout
  - debug: 
      msg: echo "{{VPC_ID.stdout}}"

  - name: create subnet
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{VPC_ID.stdout}}"
      cidr: 172.16.0.0/24
      map_public: yes
      tags:
        Name: Database Subnet
    register: database_subnet

  - name: to display subnet id
    command:  aws ec2 describe-subnets --filter Name=tag:Name,Values="Database Subnet" --query Subnets[].SubnetId 
    register: sub_id

  - debug: var=sub_id.stdout 


  - name: create internet gateway for vpc
    ec2_vpc_igw:
      vpc_id: "{{VPC_ID.stdout}}"
      state: present
      tags:
        Name: myigw
      
  - name: list myigw id
    command: aws ec2 describe-internet-gateways --filter Name=tag:Name,Values=myigw --query InternetGateways[].InternetGatewayId
    register: myigw_id

  - debug: var=myigw_id.stdout
